# Generated by Django 5.0.6 on 2026-09-01 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Mi hogar', max_length=80, verbose_name='nombre')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('office', 'Oficina'), ('commercial', 'Local comercial')], default='apartment', max_length=20, verbose_name='tipo')),
                ('address_line', models.CharField(blank=True, max_length=200, verbose_name='direccion')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='barrio')),
                ('city', models.CharField(default='Bogota', max_length=80, verbose_name='ciudad')),
                ('country', models.CharField(default='Colombia', max_length=80, verbose_name='pais')),
                ('latitude', models.FloatField(verbose_name='latitud')),
                ('longitude', models.FloatField(verbose_name='longitud')),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='area m2')),
                ('build_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='anio de construccion')),
                ('notes', models.TextField(blank=True, verbose_name='notas de acceso')),
                ('is_default', models.BooleanField(default=False, verbose_name='principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hogar',
                'verbose_name_plural': 'hogares',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
