# Generated by Django 5.0.6 on 2026-09-01 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('diagnosis', '0001_initial'),
        ('households', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('urgency', models.CharField(choices=[('flexible', 'Puedo esperar'), ('this_week', 'Esta semana'), ('urgent', 'Urgente')], default='this_week', max_length=20)),
                ('search_radius_km', models.FloatField(default=5, verbose_name='radio de busqueda (km)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Publicada'), ('matched', 'Con profesional asignado'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('diagnostic_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='diagnosis.diagnosticsession')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='households.household')),
                ('selected_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_selected', to='catalog.servicecategory', verbose_name='categoria confirmada por el cliente')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_suggested', to='catalog.servicecategory', verbose_name='categoria sugerida por el sistema')),
            ],
            options={
                'verbose_name': 'solicitud de servicio',
                'verbose_name_plural': 'solicitudes de servicio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(verbose_name='distancia (km)')),
                ('status', models.CharField(choices=[('suggested', 'Sugerido'), ('contacted', 'Contactado'), ('quoted', 'Cotizo'), ('declined', 'Declino'), ('hired', 'Contratado')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='professionals.professionalprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='service_requests.servicerequest')),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidatos',
                'ordering': ['distance_km'],
            },
        ),
        migrations.AddConstraint(
            model_name='requestcandidate',
            constraint=models.UniqueConstraint(fields=('request', 'professional'), name='unique_candidate_per_request'),
        ),
    ]
