# Generated by Django 5.0.6 on 2026-09-01 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('service_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceptada'), ('scheduled', 'Agendada'), ('in_progress', 'En ejecucion'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='requested', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='visita agendada')),
                ('estimate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimado minimo')),
                ('estimate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimado maximo')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio final')),
                ('client_notes', models.TextField(blank=True, verbose_name='notas del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='professionals.professionalprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='service_requests.servicerequest')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceptada'), ('scheduled', 'Agendada'), ('in_progress', 'En ejecucion'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'verbose_name': 'evento de la orden',
                'verbose_name_plural': 'eventos de la orden',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order')),
            ],
            options={
                'verbose_name': 'calificacion',
                'verbose_name_plural': 'calificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
