# Generated by Django 5.0.6 on 2026-09-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descripcion')),
                ('icon_key', models.CharField(blank=True, max_length=40, verbose_name='icono')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Terminos que el diagnostico usa para sugerir esta categoria.', verbose_name='palabras clave')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria de servicio',
                'verbose_name_plural': 'categorias de servicio',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='tarifa minima')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='tarifa maxima')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='horas estimadas')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.servicecategory')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['category__sort_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_service_slug_per_category'),
        ),
    ]
