# Generated by Django 5.0.6 on 2026-09-01 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='codigo')),
                ('text', models.CharField(max_length=200, verbose_name='pregunta')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='ayuda')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'pregunta de diagnostico',
                'verbose_name_plural': 'preguntas de diagnostico',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=40, verbose_name='valor')),
                ('label', models.CharField(max_length=120, verbose_name='etiqueta')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('weights', models.JSONField(blank=True, default=dict, verbose_name='pesos por categoria')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='diagnosis.diagnosticquestion')),
            ],
            options={
                'verbose_name': 'opcion de diagnostico',
                'verbose_name_plural': 'opciones de diagnostico',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='descripcion del problema')),
                ('status', models.CharField(choices=[('draft', 'En curso'), ('suggested', 'Sugerencia entregada'), ('confirmed', 'Confirmada por el cliente'), ('discarded', 'Descartada por el cliente')], default='draft', max_length=20)),
                ('confidence', models.FloatField(default=0, verbose_name='confianza')),
                ('rationale', models.CharField(blank=True, max_length=300, verbose_name='motivo de la sugerencia')),
                ('ranking', models.JSONField(blank=True, default=list, verbose_name='ranking de categorias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='households.household')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_suggestions', to='catalog.servicecategory', verbose_name='categoria sugerida')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesion de diagnostico',
                'verbose_name_plural': 'sesiones de diagnostico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.CharField(blank=True, max_length=200)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.diagnosticoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosticquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnosis.diagnosticsession')),
            ],
            options={
                'verbose_name': 'respuesta de diagnostico',
                'verbose_name_plural': 'respuestas de diagnostico',
            },
        ),
        migrations.AddConstraint(
            model_name='diagnosticoption',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_option_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_answer_per_question'),
        ),
    ]
