# Generated by Django 5.0.6 on 2026-09-01 19:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, verbose_name='nombre publico')),
                ('headline', models.CharField(blank=True, max_length=140, verbose_name='titular')),
                ('bio', models.TextField(blank=True, verbose_name='descripcion')),
                ('latitude', models.FloatField(verbose_name='latitud')),
                ('longitude', models.FloatField(verbose_name='longitud')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='barrio')),
                ('city', models.CharField(default='Bogota', max_length=80, verbose_name='ciudad')),
                ('coverage_radius_km', models.FloatField(default=8, verbose_name='radio de cobertura (km)')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='calificacion')),
                ('jobs_completed', models.PositiveIntegerField(default=0, verbose_name='servicios completados')),
                ('response_time_minutes', models.PositiveIntegerField(default=60, verbose_name='tiempo de respuesta')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verificado por Serviprox')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('accepts_urgent', models.BooleanField(default=False, verbose_name='atiende urgencias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'ordering': ['-rating_avg', '-jobs_completed'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'trabajo del portafolio',
                'verbose_name_plural': 'portafolio',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'franja de disponibilidad',
                'verbose_name_plural': 'franjas de disponibilidad',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='catalog.servicecategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'servicio del profesional',
                'verbose_name_plural': 'servicios del profesional',
            },
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='professiona_latitud_a5301c_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalservice',
            constraint=models.UniqueConstraint(fields=('profile', 'category'), name='unique_category_per_professional'),
        ),
    ]
